import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AlertProvider } from "./scripts/Alert.context";
import { AlertContainer } from "./components/container/Alert.container";
import { ConfirmProvider } from "./scripts/Confirm.context";
import { ConfirmContainer } from "./components/container/Confirm.container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfirmProvider>
          <AlertProvider>
            <ConfirmContainer />
            <AlertContainer />
            {children}
          </AlertProvider>
        </ConfirmProvider>
      </body>
    </html>
  );
}